[package]
name = "Examples"
version = "0.0.0"

[addresses]
MyModule = "0x7dc22d905417028454a3de4d3e3f666eff8914684b4ccea7d833c0c4e3346242"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-node-v1.2.0" }